### ISSUE TITLE
Does spelling affect code or just text?

### ISSUE THREAD

**Issue by Ffisegydd** [AstroCB/Stack-Exchange-Editor-Toolkit#41]
Hey. 

Thanks for posting this repo earlier, looks awesome and we're starting to put together some regexes for Python-based things.

One question we have though: **do the spelling rules affect words that are inside code blocks?**

For example the numerical Python package is `NumPy` but due to the naming conventions of Python it's called `numpy` in code, so some code might look like

~~~
import numpy as np
print(np.__version__)
~~~

It would be nice to replace `numpy` with `NumPy` in text, but if you did that to code you'd break the code.

If you could confirm that, that'd be great. I'd try to read the JS and see but that would make my head hurt :3

Cheers.

Ffisegydd.

**Comment by AstroCB** [comment]
Fortunately, [this was fixed](https://github.com/AstroCB/Stack-Exchange-Editor-Toolkit/issues/6) a while ago, and it made the script a lot more reliable.
