### ISSUE TITLE
Editor preview window doesn't update after fixing

### ISSUE THREAD

**Issue by SathyaBhat** [AstroCB/Stack-Exchange-Editor-Toolkit#46]
Minor issue, but the editor preview window doesn't show the updated changes after I click on Fix button unless I enter something in the body manually.

**Comment by AstroCB** [comment]
I looked a bit at this, and I'm not sure how we can fix it. The box requires a keypress to update, which we can technically simulate, but I haven't gotten that to work yet.

**Comment by stephenostermiller** [comment]
Emulating key presses to get changes to show up is implemented in 1.6.0.
