### ISSUE TITLE
Don't fix spelling in code blocks?

### ISSUE THREAD

**Issue by ExplodingCabbage** [AstroCB/Stack-Exchange-Editor-Toolkit#54]
I just came across, futilely voted to reject, and finally rolled back [this fuck-up](http://stackoverflow.com/review/suggested-edits/9100342), and recognised the edit messages as originating from this tool (of which I'm aware, but not yet a user).

In the suggested edit, the editor has modified not only the spelling of comments copied verbatim from files in Rails, but also of *identifiers* in code. I assume these were automated changes.

Looking at the gif in the README showing how the tool behaves, it seems to me that a mistake like this would be pretty hard to spot from the editor's perspective.

Perhaps it would be better if the capitalization corrections didn't touch code blocks at all? There are certainly cases where you'd want to fix up the spelling/capitalization of comments, but my gut tells me that spelling fixes in code are going to be harmful more often than they're helpful and that it's wiser to err on safety by not having the tool do them at all.

I'm not a user of the tool, though, so perhaps I'm not in the best position to make that judgement. What do you think?

**Comment by AstroCB** [comment]
It...shouldn't, to say the least. Corrections within code blocks were fixed a long time ago, so that user appears to be running a very old version of the script.

See #6 for more information.
