### ISSUE TITLE
Test Suite

### ISSUE THREAD

**Issue by nwinkler** [AstroCB/Stack-Exchange-Editor-Toolkit#55]
Did you ever think about creating a test suite for the toolkit? Something like a set of test cases and expected outcomes and a means for running the tests. Something like Mocha or Karma. This could then be run using something like Travis-CI when someone makes changes.

I see a lot of benefit from doing this, especially with regards to the use of regular expressions.

Let me know if that's something you're interested in or have thought about...

**Comment by AstroCB** [comment]
Something like that would probably be pretty useful; I haven't been working on the script recently, but that would be nice to have.

**Comment by nwinkler** [comment]
I have started work on a test suite and continuous integration. You can see the work in progress here:

* The `test` branch in my fork of your project: https://github.com/nwinkler/Stack-Exchange-Editor-Toolkit/tree/test
* The Travis-CI build, which runs the tests using Mocha and PhantomJS in a headless browser: https://travis-ci.org/nwinkler/Stack-Exchange-Editor-Toolkit

So far I've only added a couple of tests for the replacements, but they show how to write and run the tests. I'll add some more and I'll try to clean up the test setup as well to make it simpler to use. Once I've done that, I'll create a PR.

Feel free to take a look and provide feedback on the work in progress...

**Comment by Unihedro** [comment]
`should handle git/Git end of sentence in the body`

... yes

**Comment by nwinkler** [comment]
Only 24 tests so far, but they're all working. I plan on adding tests for the other replacements as well. A next step would then be to adjust the word boundaries so that they all work in a similar manner.
