### ISSUE TITLE
Malformed Editor Toolkit icon

### ISSUE THREAD

**Issue by DavidPostill** [AstroCB/Stack-Exchange-Editor-Toolkit#59]
The  Editor Toolkit icon appears to be malformed (vertically stretched) an not aligned with the rest of the icons on Firefox (screenshot is for v45 but it was also an issue on v44)

![screenshot - 10_03_2016 10_04_07](https://cloud.githubusercontent.com/assets/7079224/13666065/7cf41de2-e6a7-11e5-9272-f264fcc40331.png)

**Comment by AstroCB** [comment]
Looks like this is the result of SE doing some design updates that may have screwed up the way we have traditionally inserted the button – I'll take a look.
