### ISSUE TITLE
Supersized Magic Wand on Chrome

### ISSUE THREAD

**Issue by riggsfolly** [AstroCB/Stack-Exchange-Editor-Toolkit#64]
Magic Editor V1.6.0.0
Chrome Version 64.0.3282.167 (Official Build) (32-bit)
Site - StackOverflow

Strange issue in Chrome browser
I am getting a supersized magic wand and stars off to the right of any actively editable  Question/Answer box.
FF has a nice little icon on the Icon bar, but chrome is doing something completely odd.

![untitled-1](https://user-images.githubusercontent.com/10671783/36532281-2f848544-17b8-11e8-8783-b9730593ef4e.jpg)

**Comment by stephenostermiller** [comment]
This appears to be a bug in a fork of this project and not in this project itself.
